package com.sybinal.shop.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Article {

	private String articleCategoryName;
	
	private String title;
	
	private String updateTimeFrom;
	private String updateTimeTo;



	public String getUpdateTimeFrom() {
		return updateTimeFrom;
	}

	public void setUpdateTimeFrom(String updateTimeFrom) {
		this.updateTimeFrom = updateTimeFrom;
	}

	public String getUpdateTimeTo() {
		return updateTimeTo;
	}

	public void setUpdateTimeTo(String updateTimeTo) {
		this.updateTimeTo = updateTimeTo;
	}
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.id
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	private Integer id;
	public String getArticleCategoryName() {
		return articleCategoryName;
	}

	public void setArticleCategoryName(String articleCategoryName) {
		this.articleCategoryName = articleCategoryName;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.category
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	private Integer category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.update_time
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.update_user_id
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	private String updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article.content
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.id
	 * @return  the value of article.id
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.id
	 * @param id  the value for article.id
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.category
	 * @return  the value of article.category
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public Integer getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.category
	 * @param category  the value for article.category
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public void setCategory(Integer category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.update_time
	 * @return  the value of article.update_time
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") 
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.update_time
	 * @param updateTime  the value for article.update_time
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.update_user_id
	 * @return  the value of article.update_user_id
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.update_user_id
	 * @param updateUserId  the value for article.update_user_id
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article.content
	 * @return  the value of article.content
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article.content
	 * @param content  the value for article.content
	 * @mbggenerated  Sat Oct 22 11:40:01 JST 2016
	 */
	public void setContent(String content) {
		this.content = content;
	}
}