package com.sybinal.shop.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ArticleCategory {

	private String updateTimeFrom;
	private String updateTimeTo;



	public String getUpdateTimeFrom() {
		return updateTimeFrom;
	}

	public void setUpdateTimeFrom(String updateTimeFrom) {
		this.updateTimeFrom = updateTimeFrom;
	}

	public String getUpdateTimeTo() {
		return updateTimeTo;
	}

	public void setUpdateTimeTo(String updateTimeTo) {
		this.updateTimeTo = updateTimeTo;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category.category_id
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category.category_name
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	private String categoryName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category.update_user_id
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	private String updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column article_category.update_time
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")  
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category.category_id
	 * @return  the value of article_category.category_id
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category.category_id
	 * @param categoryId  the value for article_category.category_id
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category.category_name
	 * @return  the value of article_category.category_name
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	public String getCategoryName() {
		return categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category.category_name
	 * @param categoryName  the value for article_category.category_name
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category.update_user_id
	 * @return  the value of article_category.update_user_id
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	public String getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category.update_user_id
	 * @param updateUserId  the value for article_category.update_user_id
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column article_category.update_time
	 * @return  the value of article_category.update_time
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") 
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column article_category.update_time
	 * @param updateTime  the value for article_category.update_time
	 * @mbggenerated  Sat Oct 22 12:04:01 JST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}