package com.sybinal.shop.model;

import com.sybinal.shop.utils.Page;

public class Contect extends Page {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contect.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contect.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contect.name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contect.mobile
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contect.contact_flag
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer contactFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column contect.address
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String address;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contect.id
	 * @return  the value of contect.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	
	
	private int paymentType;
	
	
	public int getPaymentType() {
		return paymentType;
	}

	public void setPaymentType(int paymentType) {
		this.paymentType = paymentType;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contect.id
	 * @param id  the value for contect.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contect.user_id
	 * @return  the value of contect.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contect.user_id
	 * @param userId  the value for contect.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contect.name
	 * @return  the value of contect.name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contect.name
	 * @param name  the value for contect.name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contect.mobile
	 * @return  the value of contect.mobile
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contect.mobile
	 * @param mobile  the value for contect.mobile
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contect.contact_flag
	 * @return  the value of contect.contact_flag
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getContactFlag() {
		return contactFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contect.contact_flag
	 * @param contactFlag  the value for contect.contact_flag
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setContactFlag(Integer contactFlag) {
		this.contactFlag = contactFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column contect.address
	 * @return  the value of contect.address
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column contect.address
	 * @param address  the value for contect.address
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setAddress(String address) {
		this.address = address;
	}
}