package com.sybinal.shop.model;

import java.util.List;

public class Option {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column option.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column option.name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column option.type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column option.id
	 * @return  the value of option.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column option.id
	 * @param id  the value for option.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column option.name
	 * @return  the value of option.name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column option.name
	 * @param name  the value for option.name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column option.type
	 * @return  the value of option.type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column option.type
	 * @param type  the value for option.type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}
	
	private List<OptionValue> optionValue;

	public List<OptionValue> getOptionValue() {
		return optionValue;
	}

	public void setOptionValue(List<OptionValue> optionValue) {
		this.optionValue = optionValue;
	}
}