package com.sybinal.shop.model;

public class OptionValue {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column option_value.id
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column option_value.option_id
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	private Integer optionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column option_value.name
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column option_value.id
	 * @return  the value of option_value.id
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column option_value.id
	 * @param id  the value for option_value.id
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column option_value.option_id
	 * @return  the value of option_value.option_id
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	public Integer getOptionId() {
		return optionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column option_value.option_id
	 * @param optionId  the value for option_value.option_id
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	public void setOptionId(Integer optionId) {
		this.optionId = optionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column option_value.name
	 * @return  the value of option_value.name
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column option_value.name
	 * @param name  the value for option_value.name
	 * @mbg.generated  Fri Oct 21 14:28:00 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}
}