package com.sybinal.shop.model;

import java.util.Date;
import java.util.List;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.sybinal.shop.model.Contect;
import com.sybinal.shop.utils.Page;

public class Order extends Page {

	private String orderNum;

	private Integer price;

	private Integer paymentFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.contact_name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String contactName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.contact_mobile
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String contactMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.contact_address
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String contactAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.message
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String message;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.status
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.create_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss") 
	private Date createTime;

	private OrderItem orderItem;
	
	private String StartDate;

	private String endDate;

	private Contect contect;
	
	private List<OrderHistory> orderHistoryList;
	
	public Contect getContect() {
		return contect;
	}

	public void setContect(Contect contect) {
		this.contect = contect;
	}

	private List<Contect> contectList;
	
	private String startPrice;
	
	private String endPrice;
	
	// 详细详细预留
	private List<OrderItem> orderItemList;
	// 物流信息预留
	private List<Logistics> logisticsList;
	// 支付信息预留
	private List<PaymentHistory> paymentHistoryList;
	
	public List<OrderItem> getOrderItemList() {
		return orderItemList;
	}

	public void setOrderItemList(List<OrderItem> orderItemList) {
		this.orderItemList = orderItemList;
	}


	public List<Logistics> getLogisticsList() {
		return logisticsList;
	}

	public void setLogisticsList(List<Logistics> logisticsList) {
		this.logisticsList = logisticsList;
	}

	public List<PaymentHistory> getPaymentHistoryList() {
		return paymentHistoryList;
	}

	public void setPaymentHistoryList(List<PaymentHistory> paymentHistoryList) {
		this.paymentHistoryList = paymentHistoryList;
	}

	public OrderItem getOrderItem() {
		return orderItem;
	}

	public String getStartPrice() {
		return startPrice;
	}

	public void setStartPrice(String startPrice) {
		this.startPrice = startPrice;
	}

	public String getEndPrice() {
		return endPrice;
	}

	public void setEndPrice(String endPrice) {
		this.endPrice = endPrice;
	}

	public void setOrderItem(OrderItem orderItem) {
		this.orderItem = orderItem;
	}

	public String getStartDate() {
		return StartDate;
	}

	public void setStartDate(String startDate) {
		StartDate = startDate;
	}

	public String getEndDate() {
		return endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.order_num
	 * @param orderNum  the value for order.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.payment_flag
	 * @return  the value of order.payment_flag
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getPaymentFlag() {
		return paymentFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.payment_flag
	 * @param paymentFlag  the value for order.payment_flag
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setPaymentFlag(Integer paymentFlag) {
		this.paymentFlag = paymentFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.user_id
	 * @return  the value of order.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.user_id
	 * @param userId  the value for order.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.contact_name
	 * @return  the value of order.contact_name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.contact_name
	 * @param contactName  the value for order.contact_name
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.contact_mobile
	 * @return  the value of order.contact_mobile
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getContactMobile() {
		return contactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.contact_mobile
	 * @param contactMobile  the value for order.contact_mobile
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setContactMobile(String contactMobile) {
		this.contactMobile = contactMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.contact_address
	 * @return  the value of order.contact_address
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getContactAddress() {
		return contactAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.contact_address
	 * @param contactAddress  the value for order.contact_address
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setContactAddress(String contactAddress) {
		this.contactAddress = contactAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.message
	 * @return  the value of order.message
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.message
	 * @param message  the value for order.message
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.status
	 * @return  the value of order.status
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.status
	 * @param status  the value for order.status
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.type
	 * @return  the value of order.type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.type
	 * @param type  the value for order.type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.create_time
	 * @return  the value of order.create_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public List<Contect> getContectList() {
		return contectList;
	}

	public void setContectList(List<Contect> contectList) {
		this.contectList = contectList;
	}

	public List<OrderHistory> getOrderHistoryList() {
		return orderHistoryList;
	}

	public void setOrderHistoryList(List<OrderHistory> orderHistoryList) {
		this.orderHistoryList = orderHistoryList;
	}

}