package com.sybinal.shop.model;

import java.util.List;

public class OrderItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.product_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.price
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_item.quantity
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer userId;
	
	private Integer quantity;
	///////////////
	private String jsonData;
	
	private Integer skuId;
	
	private String optionValueKeyGroup;
	//////////////////////////
	
	private List<Product> productList;

	public List<Product> getProductList() {
		return productList;
	}

	public void setProductList(List<Product> productList) {
		this.productList = productList;
	}
 
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.order_num
	 * @param orderNum  the value for order_item.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.product_id
	 * @return  the value of order_item.product_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.product_id
	 * @param productId  the value for order_item.product_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.price
	 * @return  the value of order_item.price
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_item.price
	 * @param price  the value for order_item.price
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_item.quantity
	 * @return  the value of order_item.quantity
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getQuantity() {
		return quantity;
	}

	
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	
	public Integer getUserId() {
		return userId;
	}

	
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getJsonData() {
		return jsonData;
	}

	public void setJsonData(String jsonData) {
		this.jsonData = jsonData;
	}

	public Integer getSkuId() {
		return skuId;
	}

	public void setSkuId(Integer skuId) {
		this.skuId = skuId;
	}

	public String getOptionValueKeyGroup() {
		return optionValueKeyGroup;
	}

	public void setOptionValueKeyGroup(String optionValueKeyGroup) {
		this.optionValueKeyGroup = optionValueKeyGroup;
	}
	
}