package com.sybinal.shop.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class OrderHistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_history.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_history.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_history.status
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_history.note
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String note;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_history.update_user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_history.create_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")  
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_history.id
	 * @return  the value of order_history.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	
	
	
	private String userName;
	
	
	
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_history.id
	 * @param id  the value for order_history.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_history.order_num
	 * @return  the value of order_history.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_history.order_num
	 * @param orderNum  the value for order_history.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_history.status
	 * @return  the value of order_history.status
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_history.status
	 * @param status  the value for order_history.status
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_history.note
	 * @return  the value of order_history.note
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getNote() {
		return note;
	}

	
	public void setNote(Object obj) {
		if(obj instanceof Integer){
			if((Integer)obj==1){
				this.note = "已下单";
			}else if((Integer)obj==4){
				this.note = "订单已取消";
			}else if((Integer)obj==2){
				this.note = "配送中";
			}else if((Integer)obj==3){
				this.note = "配送完成";
			}else{
				this.note = "订单编辑中";
			}
		}else if(obj instanceof String){
			this.note = obj.toString();
		}
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_history.update_user_id
	 * @return  the value of order_history.update_user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_history.update_user_id
	 * @param updateUserId  the value for order_history.update_user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_history.create_time
	 * @return  the value of order_history.create_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8") 
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_history.create_time
	 * @param createTime  the value for order_history.create_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	
}