package com.sybinal.shop.model;

import java.util.Date;

public class ProductImage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_image.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_image.product_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_image.url
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_image.update_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_image.update_user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer updateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_image.explain
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String explain;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_image.id
	 * @return  the value of product_image.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_image.id
	 * @param id  the value for product_image.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_image.product_id
	 * @return  the value of product_image.product_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_image.product_id
	 * @param productId  the value for product_image.product_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_image.url
	 * @return  the value of product_image.url
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_image.url
	 * @param url  the value for product_image.url
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_image.update_time
	 * @return  the value of product_image.update_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_image.update_time
	 * @param updateTime  the value for product_image.update_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_image.update_user_id
	 * @return  the value of product_image.update_user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getUpdateUserId() {
		return updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_image.update_user_id
	 * @param updateUserId  the value for product_image.update_user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setUpdateUserId(Integer updateUserId) {
		this.updateUserId = updateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_image.explain
	 * @return  the value of product_image.explain
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getExplain() {
		return explain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_image.explain
	 * @param explain  the value for product_image.explain
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setExplain(String explain) {
		this.explain = explain;
	}
}