package com.sybinal.shop.model;

public class ProductOptionInfo {
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_option_info.id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_option_info.product_id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_option_info.option_id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    private Integer optionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_option_info.id
     *
     * @return the value of product_option_info.id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_option_info.id
     *
     * @param id the value for product_option_info.id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_option_info.product_id
     *
     * @return the value of product_option_info.product_id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_option_info.product_id
     *
     * @param productId the value for product_option_info.product_id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_option_info.option_id
     *
     * @return the value of product_option_info.option_id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    public Integer getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_option_info.option_id
     *
     * @param optionId the value for product_option_info.option_id
     *
     * @mbg.generated Wed Oct 26 10:17:30 CST 2016
     */
    public void setOptionId(Integer optionId) {
        this.optionId = optionId;
    }
}