package com.sybinal.shop.model;

public class ProductOptionKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_option.option_value_ids
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	private String optionValueIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_option.option_value_names
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	private String optionValueNames;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_option.product_id
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	private Integer productId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_option.option_value_ids
	 * @return  the value of product_option.option_value_ids
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public String getOptionValueIds() {
		return optionValueIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_option.option_value_ids
	 * @param optionValueIds  the value for product_option.option_value_ids
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public void setOptionValueIds(String optionValueIds) {
		this.optionValueIds = optionValueIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_option.option_value_names
	 * @return  the value of product_option.option_value_names
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public String getOptionValueNames() {
		return optionValueNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_option.option_value_names
	 * @param optionValueNames  the value for product_option.option_value_names
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public void setOptionValueNames(String optionValueNames) {
		this.optionValueNames = optionValueNames;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_option.product_id
	 * @return  the value of product_option.product_id
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_option.product_id
	 * @param productId  the value for product_option.product_id
	 * @mbg.generated  Fri Oct 21 14:41:07 CST 2016
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}
}