package com.sybinal.shop.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public ProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("`p`.`id` =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("`p`.`name` like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNull() {
			addCriterion("category_id is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNotNull() {
			addCriterion("category_id is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdEqualTo(Integer value) {
			addCriterion("`p`.`category_id` =", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotEqualTo(Integer value) {
			addCriterion("category_id <>", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThan(Integer value) {
			addCriterion("category_id >", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("category_id >=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThan(Integer value) {
			addCriterion("category_id <", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
			addCriterion("category_id <=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIn(List<Integer> values) {
			addCriterion("category_id in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotIn(List<Integer> values) {
			addCriterion("category_id not in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
			addCriterion("category_id between", value1, value2, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
			addCriterion("category_id not between", value1, value2, "categoryId");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainIsNull() {
			addCriterion("general_explain is null");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainIsNotNull() {
			addCriterion("general_explain is not null");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainEqualTo(String value) {
			addCriterion("general_explain =", value, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainNotEqualTo(String value) {
			addCriterion("general_explain <>", value, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainGreaterThan(String value) {
			addCriterion("general_explain >", value, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainGreaterThanOrEqualTo(String value) {
			addCriterion("general_explain >=", value, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainLessThan(String value) {
			addCriterion("general_explain <", value, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainLessThanOrEqualTo(String value) {
			addCriterion("general_explain <=", value, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainLike(String value) {
			addCriterion("general_explain like", value, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainNotLike(String value) {
			addCriterion("general_explain not like", value, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainIn(List<String> values) {
			addCriterion("general_explain in", values, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainNotIn(List<String> values) {
			addCriterion("general_explain not in", values, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainBetween(String value1, String value2) {
			addCriterion("general_explain between", value1, value2, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andGeneralExplainNotBetween(String value1, String value2) {
			addCriterion("general_explain not between", value1, value2, "generalExplain");
			return (Criteria) this;
		}

		public Criteria andDiscountIsNull() {
			addCriterion("discount is null");
			return (Criteria) this;
		}

		public Criteria andDiscountIsNotNull() {
			addCriterion("discount is not null");
			return (Criteria) this;
		}

		public Criteria andDiscountEqualTo(Integer value) {
			addCriterion("discount =", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotEqualTo(Integer value) {
			addCriterion("discount <>", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountGreaterThan(Integer value) {
			addCriterion("discount >", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountGreaterThanOrEqualTo(Integer value) {
			addCriterion("discount >=", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountLessThan(Integer value) {
			addCriterion("discount <", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountLessThanOrEqualTo(Integer value) {
			addCriterion("discount <=", value, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountIn(List<Integer> values) {
			addCriterion("discount in", values, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotIn(List<Integer> values) {
			addCriterion("discount not in", values, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountBetween(Integer value1, Integer value2) {
			addCriterion("discount between", value1, value2, "discount");
			return (Criteria) this;
		}

		public Criteria andDiscountNotBetween(Integer value1, Integer value2) {
			addCriterion("discount not between", value1, value2, "discount");
			return (Criteria) this;
		}

		public Criteria andShopPriceIsNull() {
			addCriterion("shop_price is null");
			return (Criteria) this;
		}

		public Criteria andShopPriceIsNotNull() {
			addCriterion("shop_price is not null");
			return (Criteria) this;
		}

		public Criteria andShopPriceEqualTo(Integer value) {
			addCriterion("shop_price =", value, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceNotEqualTo(Integer value) {
			addCriterion("shop_price <>", value, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceGreaterThan(Integer value) {
			addCriterion("shop_price >", value, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("`p`.`shop_price` >=", value, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceLessThan(Integer value) {
			addCriterion("shop_price <", value, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceLessThanOrEqualTo(Integer value) {
			addCriterion("`p`.`shop_price` <=", value, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceIn(List<Integer> values) {
			addCriterion("shop_price in", values, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceNotIn(List<Integer> values) {
			addCriterion("shop_price not in", values, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceBetween(Integer value1, Integer value2) {
			addCriterion("shop_price between", value1, value2, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andShopPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("shop_price not between", value1, value2, "shopPrice");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Integer value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Integer value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Integer value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Integer value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Integer value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Integer> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Integer> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Integer value1, Integer value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andExternalIdIsNull() {
			addCriterion("external_id is null");
			return (Criteria) this;
		}

		public Criteria andExternalIdIsNotNull() {
			addCriterion("external_id is not null");
			return (Criteria) this;
		}

		public Criteria andExternalIdEqualTo(String value) {
			addCriterion("external_id =", value, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdNotEqualTo(String value) {
			addCriterion("external_id <>", value, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdGreaterThan(String value) {
			addCriterion("external_id >", value, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdGreaterThanOrEqualTo(String value) {
			addCriterion("external_id >=", value, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdLessThan(String value) {
			addCriterion("external_id <", value, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdLessThanOrEqualTo(String value) {
			addCriterion("external_id <=", value, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdLike(String value) {
			addCriterion("external_id like", value, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdNotLike(String value) {
			addCriterion("external_id not like", value, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdIn(List<String> values) {
			addCriterion("external_id in", values, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdNotIn(List<String> values) {
			addCriterion("external_id not in", values, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdBetween(String value1, String value2) {
			addCriterion("external_id between", value1, value2, "externalId");
			return (Criteria) this;
		}

		public Criteria andExternalIdNotBetween(String value1, String value2) {
			addCriterion("external_id not between", value1, value2, "externalId");
			return (Criteria) this;
		}

		public Criteria andQuantityIsNull() {
			addCriterion("quantity is null");
			return (Criteria) this;
		}

		public Criteria andQuantityIsNotNull() {
			addCriterion("quantity is not null");
			return (Criteria) this;
		}

		public Criteria andQuantityEqualTo(Integer value) {
			addCriterion("quantity =", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotEqualTo(Integer value) {
			addCriterion("quantity <>", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityGreaterThan(Integer value) {
			addCriterion("quantity >", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
			addCriterion("quantity >=", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityLessThan(Integer value) {
			addCriterion("quantity <", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityLessThanOrEqualTo(Integer value) {
			addCriterion("quantity <=", value, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityIn(List<Integer> values) {
			addCriterion("quantity in", values, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotIn(List<Integer> values) {
			addCriterion("quantity not in", values, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityBetween(Integer value1, Integer value2) {
			addCriterion("quantity between", value1, value2, "quantity");
			return (Criteria) this;
		}

		public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
			addCriterion("quantity not between", value1, value2, "quantity");
			return (Criteria) this;
		}

		public Criteria andHotIsNull() {
			addCriterion("hot is null");
			return (Criteria) this;
		}

		public Criteria andHotIsNotNull() {
			addCriterion("hot is not null");
			return (Criteria) this;
		}

		public Criteria andHotEqualTo(Integer value) {
			addCriterion("`p`.`hot` =", value, "hot");
			return (Criteria) this;
		}

		public Criteria andHotNotEqualTo(Integer value) {
			addCriterion("hot <>", value, "hot");
			return (Criteria) this;
		}

		public Criteria andHotGreaterThan(Integer value) {
			addCriterion("hot >", value, "hot");
			return (Criteria) this;
		}

		public Criteria andHotGreaterThanOrEqualTo(Integer value) {
			addCriterion("hot >=", value, "hot");
			return (Criteria) this;
		}

		public Criteria andHotLessThan(Integer value) {
			addCriterion("hot <", value, "hot");
			return (Criteria) this;
		}

		public Criteria andHotLessThanOrEqualTo(Integer value) {
			addCriterion("hot <=", value, "hot");
			return (Criteria) this;
		}

		public Criteria andHotIn(List<Integer> values) {
			addCriterion("hot in", values, "hot");
			return (Criteria) this;
		}

		public Criteria andHotNotIn(List<Integer> values) {
			addCriterion("hot not in", values, "hot");
			return (Criteria) this;
		}

		public Criteria andHotBetween(Integer value1, Integer value2) {
			addCriterion("hot between", value1, value2, "hot");
			return (Criteria) this;
		}

		public Criteria andHotNotBetween(Integer value1, Integer value2) {
			addCriterion("hot not between", value1, value2, "hot");
			return (Criteria) this;
		}

		public Criteria andProductStatusIsNull() {
			addCriterion("product_status is null");
			return (Criteria) this;
		}

		public Criteria andProductStatusIsNotNull() {
			addCriterion("product_status is not null");
			return (Criteria) this;
		}

		public Criteria andProductStatusEqualTo(Integer value) {
			addCriterion("`p`.product_status =", value, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusNotEqualTo(Integer value) {
			addCriterion("product_status <>", value, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusGreaterThan(Integer value) {
			addCriterion("product_status >", value, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("product_status >=", value, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusLessThan(Integer value) {
			addCriterion("product_status <", value, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusLessThanOrEqualTo(Integer value) {
			addCriterion("product_status <=", value, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusIn(List<Integer> values) {
			addCriterion("product_status in", values, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusNotIn(List<Integer> values) {
			addCriterion("product_status not in", values, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusBetween(Integer value1, Integer value2) {
			addCriterion("product_status between", value1, value2, "productStatus");
			return (Criteria) this;
		}

		public Criteria andProductStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("product_status not between", value1, value2, "productStatus");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagIsNull() {
			addCriterion("inventory_flag is null");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagIsNotNull() {
			addCriterion("inventory_flag is not null");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagEqualTo(Integer value) {
			addCriterion("inventory_flag =", value, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagNotEqualTo(Integer value) {
			addCriterion("inventory_flag <>", value, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagGreaterThan(Integer value) {
			addCriterion("inventory_flag >", value, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("inventory_flag >=", value, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagLessThan(Integer value) {
			addCriterion("inventory_flag <", value, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagLessThanOrEqualTo(Integer value) {
			addCriterion("inventory_flag <=", value, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagIn(List<Integer> values) {
			addCriterion("inventory_flag in", values, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagNotIn(List<Integer> values) {
			addCriterion("inventory_flag not in", values, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagBetween(Integer value1, Integer value2) {
			addCriterion("inventory_flag between", value1, value2, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andInventoryFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("inventory_flag not between", value1, value2, "inventoryFlag");
			return (Criteria) this;
		}

		public Criteria andDefaultImgIsNull() {
			addCriterion("default_img is null");
			return (Criteria) this;
		}

		public Criteria andDefaultImgIsNotNull() {
			addCriterion("default_img is not null");
			return (Criteria) this;
		}

		public Criteria andDefaultImgEqualTo(String value) {
			addCriterion("default_img =", value, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgNotEqualTo(String value) {
			addCriterion("default_img <>", value, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgGreaterThan(String value) {
			addCriterion("default_img >", value, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgGreaterThanOrEqualTo(String value) {
			addCriterion("default_img >=", value, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgLessThan(String value) {
			addCriterion("default_img <", value, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgLessThanOrEqualTo(String value) {
			addCriterion("default_img <=", value, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgLike(String value) {
			addCriterion("default_img like", value, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgNotLike(String value) {
			addCriterion("default_img not like", value, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgIn(List<String> values) {
			addCriterion("default_img in", values, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgNotIn(List<String> values) {
			addCriterion("default_img not in", values, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgBetween(String value1, String value2) {
			addCriterion("default_img between", value1, value2, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andDefaultImgNotBetween(String value1, String value2) {
			addCriterion("default_img not between", value1, value2, "defaultImg");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNull() {
			addCriterion("update_user_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIsNotNull() {
			addCriterion("update_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdEqualTo(Integer value) {
			addCriterion("update_user_id =", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotEqualTo(Integer value) {
			addCriterion("update_user_id <>", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThan(Integer value) {
			addCriterion("update_user_id >", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("update_user_id >=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThan(Integer value) {
			addCriterion("update_user_id <", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("update_user_id <=", value, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdIn(List<Integer> values) {
			addCriterion("update_user_id in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotIn(List<Integer> values) {
			addCriterion("update_user_id not in", values, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdBetween(Integer value1, Integer value2) {
			addCriterion("update_user_id between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andUpdateUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("update_user_id not between", value1, value2, "updateUserId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIsNull() {
			addCriterion("create_user_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIsNotNull() {
			addCriterion("create_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdEqualTo(Integer value) {
			addCriterion("create_user_id =", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotEqualTo(Integer value) {
			addCriterion("create_user_id <>", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdGreaterThan(Integer value) {
			addCriterion("create_user_id >", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_user_id >=", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdLessThan(Integer value) {
			addCriterion("create_user_id <", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("create_user_id <=", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIn(List<Integer> values) {
			addCriterion("create_user_id in", values, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotIn(List<Integer> values) {
			addCriterion("create_user_id not in", values, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
			addCriterion("create_user_id between", value1, value2, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("create_user_id not between", value1, value2, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdInSelect(Integer productId) {
			addCriterion(String.format("`p`.`category_id` in (select `p2`.`category_id` from `product` AS `p2`  where `p2`.`id` = %d)", productId));
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table product
	 * @mbg.generated  Mon Oct 24 21:14:56 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 19 20:55:54 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}